language: rust
rust:
  - stable
  - beta
  - nightly
script:
  - cargo build --verbose
  - cargo test --verbose
  - cd ipfs-api; cargo build --verbose --features with-actix --no-default-features
  - cd ipfs-api; cargo test --verbose --features with-actix --no-default-features
  - cd ipfs-api; cargo build --verbose --features with-hyper-rustls --no-default-features
  - cd ipfs-api; cargo test --verbose --features with-hyper-rustls --no-default-features
