language: rust
rust:
  - stable
  - beta
  - nightly
script:
  - cargo build --verbose
  - cargo test --verbose
  - cd ipfs-api; cargo build --verbose --features actix --no-default-features
  - cd ipfs-api; cargo test --verbose --features actix --no-default-features
  - cd ipfs-api; cargo build --verbose --features builder
  - cd ipfs-api; cargo test --verbose --features builder
  - cd ipfs-api; cargo test --verbose --features actix builder --no-default-features
